### ISSUE TITLE
GUI for datapetting

### ISSUE THREAD

**Issue by wucke13** [wucke13/streetmap#1]
Lads and ladys, we need a way to edit our data. To do so, it often is necessary to select datasets from our existing data, which suggests to do this selection through the given interface (which already supports selection). What do you think?

**Comment by dwdv** [comment]
Alright, what is truly missing feature-wise as of the latest commit? Is moving nodes and reattching edges to other nodes essential for the sake of the upcoming presentation? Do we really need a textbox that allows setting specific node coordinates?

Currently we support deleting selections, adding whole new streets with streetnames (thus making it very easy to reselect this newly created street) merely by clicking the map, marking edges and nodes as affected by accidents and constructions as well as setting the secured bit and endDate respectively. All of this is now backed by the server and synced to all clients.

The recently introduced top panel that shows up when adding a street and the context menu need some css love though—especially the buttons, the alignments and font mismatches. Could someone get behind this, please? My css-fu is too weak.
