### ISSUE TITLE
Multithreading im client browser

### ISSUE THREAD

**Issue by wucke13** [wucke13/streetmap#2]
@urschni 
Would you please consider adding multi threading on the client side?
I would suggest to use https://keithwhor.github.io/multithread.js/ to do that. I think of something like running all expensive operations (mapping, array transformation, data parsing ...) in a new threads. 

What do you think about that?

**Comment by urschni** [comment]
Hmm, could be a good idea, it seems that the update and receiving an incoming `objects`-array could be good candidates.

I've looked into multithread.js and I tested it with some functions (
even with the example given on their website) and always got an error with 
```
21:49:27.524 ReferenceError: assignment to undeclared variable len[Weitere Informationen] Multithread.js:1:2496
21:49:27.537 SyntaxError: function statement requires a name ce448577-471b-4fb3-8e89-7f7266a14368:1:8
```
 I guess this is not the tool for the task at the moment.

**Comment by wucke13** [comment]
Thats sad. Maybed have a look at their base system, web workes: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API
That should work - this API exists almost a decade.
